POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

###
POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "hudson",
  "name": "Cole Hudson",
  "password": "richard_567",
  "gender": "male",
  "location": "Chicago"
}